### ISSUE TITLE
A player can destroy targets so that they can earn points

### ISSUE THREAD

**Issue by jmcreasman** [TanksForWaiting/tanks-for-waiting#13]
GUI
* [x] Detect target collision
* [x] Inform API of target id and player_ID

API
* [x] Verify that the player is close enough that they might have hit the target
* [x] Give the player a point.
* [x] PUT the new information into the firebase database.

**Comment by Shea-Wolfe** [comment]
GUI
* [ ] Detect target collision
* [ ] Inform API of target location and player_ID

API
* [ ] Verify that there was a target where the GUI is saying
* [ ] Verify that the player is only getting one point
* [ ] PUT the new information into the firebase database.

**Comment by al-the-x** [comment]
Missing piece here is updating Firebase with target deletion... Either via the API or GUI.

**Comment by Shea-Wolfe** [comment]
PR: https://github.com/TanksForWaiting/tanks-for-waiting/pull/84

Requires a delete request with the player_id as a payload, but is functioning as expected.

**Comment by jmcreasman** [comment]
https://github.com/TanksForWaiting/tanks-for-waiting/pull/89
