### ISSUE TITLE
A player is directed to the game so the game can begin.

### ISSUE THREAD

**Issue by jmcreasman** [TanksForWaiting/tanks-for-waiting#20]

**Comment by al-the-x** [comment]
Sounds like the bootstrapping script from our conversation... So maybe just try embedding a single `<script>` tag on a completely unrelated page... `gh-pages` for the org, maybe?

**Comment by Shea-Wolfe** [comment]
Pull request https://github.com/TanksForWaiting/tanks-for-waiting/pull/35
Working endpoints so a player and game can be requested and created.  Not yet online.

**Comment by al-the-x** [comment]
1. Ask API for a player
2. Ask API for a game that includes a player
  1. API creates game in Firebase
  2. API puts the player in the game
. . .
