### ISSUE TITLE
A player can click (yes/no) to play the game to be entertained.

### ISSUE THREAD

**Issue by jmcreasman** [TanksForWaiting/tanks-for-waiting#21]
Button is going to need to work with these other issues/user stories

https://github.com/TanksForWaiting/tanks-for-waiting/issues/38

https://github.com/TanksForWaiting/tanks-for-waiting/issues/20

**Comment by Shea-Wolfe** [comment]
-User clicks button
-Post requests sent to https://cryptic-citadel-5628.herokuapp.com/api/players/
-request returns {player_id: 'HASH'}
-Post request sent to https://cryptic-citadel-5628.herokuapp.com/api/games/ with payload {player_id: 'HASH'}
-Game is created and player 'HASH' is inserted into that game.

**Comment by jmcreasman** [comment]
Button process checklist
* [ ] Button html
* [ ] Button css
* [ ] Hide canvas tag
* [ ] jquery click on button that hides button and shows canvas
* [ ] sends Ajax GET/POST requests when yes is clicked

**Comment by Shea-Wolfe** [comment]
GUI
* [ ] On button push send a POST request to https://cryptic-citadel-5628.herokuapp.com/players/
* [ ] With the info in the response from the first post make another POST request to https://cryptic-citadel-5628.herokuapp.com/games/ {player_id: HASH}
* [ ] Point your player to the correct database to read and write from.

API
* [ ] On getting a players POST request create a new player_id and send that in the response.
* [ ] On getting a games POST request with a player attached, create a new game_id and attach that player to it.
* [ ] On saving a new game PUT the position of the player to https://tanks-for-waiting.firebaseio.com/games/HASH/players/HASH {start_x: x coord, start_y: y coord}
* [ ] Send a response that allows the GUI to assign the player to read/write from the correct database.
