### ISSUE TITLE
A player can't drive through walls so there is challenge in getting to targets

### ISSUE THREAD

**Issue by Shea-Wolfe** [TanksForWaiting/tanks-for-waiting#46]
Planning:
* [x] Decide where the walls are going to be in the game.

GUI
* [x] Draw the walls on the canvas
* [x] Ensure that tanks can't drive through walls
* [x] Ensure that tanks can't get stuck in walls.

API
* [x] Make sure that targets don't spawn in walls. (pre-set target locations)

**Comment by al-the-x** [comment]
Do we have any progress on this issue?

**Comment by jmcreasman** [comment]
https://github.com/TanksForWaiting/tanks-for-waiting/pull/103

https://github.com/TanksForWaiting/tanks-for-waiting/pull/110
