### ISSUE TITLE
A target can respawn so the player doesn't run out of things to do.

### ISSUE THREAD

**Issue by Shea-Wolfe** [TanksForWaiting/tanks-for-waiting#47]
GUI
* [x] GUI can ask for a target by POSTing to api/games/game_id/targets/
* [x] GUI looks at targets in the firebase api to determine what to draw on the screen.

API
* [x] When GUI sends a POST request to the API the API puts a new target into the game. 
* [x] When GUI sends a delete request to the API for a target that succeeds (a player was close enough)  the API automatically create a new target and put it in the game.
* [x] When GUI sends a delete request to the API for a target that spawned in a wall (no player collision) the API creates a new one and puts it in the game.
* [ ] Generate a list of target locations so they don't spawn in walls but are still random.

**Comment by Shea-Wolfe** [comment]
-GUI picks a random location to spawn a target.
-GUI sends API a post request to api/targets/ with the payload {target_x: x, target_y: y, game_id, HASH}
-GUI continues on its merry way.

**Comment by al-the-x** [comment]
Add a bunch more details to the GUI side...

**Comment by Shea-Wolfe** [comment]
Probably was a large to begin.  Is currently set about medium level.

**Comment by Shea-Wolfe** [comment]
https://github.com/TanksForWaiting/tanks-for-waiting/pull/84.

Was waiting until we nailed down wall locations before creating a list of target points.
