### ISSUE TITLE
Players can see their scores so they know how well they are doing.

### ISSUE THREAD

**Issue by al-the-x** [TanksForWaiting/tanks-for-waiting#48]
* A player can only see his or her own score, not the scores of others.

----

Add more details.

GUI
* [x] a player will only be able to see the score linked to their player ID
* [x] Score will be pulled out of the firebase api, located at /games/game_id/scores/tank_id
* [x] Score will update correctly in real time.

API
* [x] players will have a score field that starts at 0
* [x] Validate incoming scores, if a player tries to get more than 1 at a time reject in some fashion.
* [x] A player earns a point when they destroy a target 
* [x] Put scores into firebase api at /games/game_id/scores/tank_id/score when the player earns a point.

**Comment by Shea-Wolfe** [comment]
GUI
* [ ] a player will only have the score linked to their player ID visible
API
* [ ] players will have a score field that starts at 0

**Comment by al-the-x** [comment]
* [ ] BOTH: Correct the location of `scores` in Firebase
* [ ] GUI: Watch score changes from Firebase
* [ ] GUI: Send target hits to API
* [ ] GUI: Watch target updates from Firebase
* [ ] GUI: Ask for another target from the API when 1 is destroyed
* [ ] API: Endpoint for hitting a target
* [ ] API: Update the score on successful hit

**Comment by al-the-x** [comment]
Needs an estimate...

**Comment by Shea-Wolfe** [comment]
Originally a Medium, with preexisting work is being downgraded in size.

**Comment by Shea-Wolfe** [comment]
PR: https://github.com/TanksForWaiting/tanks-for-waiting/pull/84

Putting the scores to /games/game_id/scores/player_id.json.  Score is automatically increased when a valid hit is recorded.

**Comment by al-the-x** [comment]
Anything left to do on the API side, @Shea-Wolfe? If not and we're just tracking effort remaining, let's remove the "API" label.

**Comment by jmcreasman** [comment]
https://github.com/TanksForWaiting/tanks-for-waiting/pull/95
