### ISSUE TITLE
A player will see a throbber so that they know their game is loading

### ISSUE THREAD

**Issue by jmcreasman** [TanksForWaiting/tanks-for-waiting#66]
* [x] Should start right after button is hit
* [x] Should end right before game loads

**Comment by al-the-x** [comment]
Related to whatever story was "A Player can start the game..." right?

**Comment by al-the-x** [comment]
Can we have a link for the PR and Story, please?

**Comment by Shea-Wolfe** [comment]
Included in release 0.1.0 since it was requested to be fixed before the full release.

https://github.com/TanksForWaiting/tanks-for-waiting/pull/65
