### ISSUE TITLE
A player's tank will remember the last direction it moved so it doesn't look funny.

### ISSUE THREAD

**Issue by Shea-Wolfe** [TanksForWaiting/tanks-for-waiting#67]
GUI
* [x] Draw the tank based on the last recorded key event.

**Comment by al-the-x** [comment]
I approve. Is this an API story, though? A `tank` should probably remember its orientation (by recording that information to Firebase), but does the API care?

**Comment by Shea-Wolfe** [comment]
I keep doing this!  I write API when I mean GUI.  Guess I'm just too wrapped up in back-end stuff.  Thanks.

**Comment by al-the-x** [comment]
Happens...

**Comment by al-the-x** [comment]
Also: 

* [ ] GUI: Record the orientation of the tank in Firebase
* [ ] GUI: Draw the tank based upon its recorded oreintation

**Comment by al-the-x** [comment]
From our last conversation, it looks like this is working, but I don't see a link to a PR... :suspect:

**Comment by Shea-Wolfe** [comment]
Pull Request: https://github.com/TanksForWaiting/tanks-for-waiting/pull/77
