### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by al-the-x** [TanksForWaiting/tanks-for-waiting#91]
* [x] Have a basic description of the product.
* [x] Have a button to start playing a tutorial
* [x] Have controls laid out.

**Comment by jmcreasman** [comment]
Details to be determined during meeting

**Comment by al-the-x** [comment]
* What is your product?
* What problem does it solve?
* How does it solve it? (3 points)
* How much does it cost?
* What do you want me to do next? (Call to Action)

**Comment by jmcreasman** [comment]
http://tanksforwaiting.github.io/#
